// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogMessageTransporter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_LogMessageTransporter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_LogMessageTransporter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_LogMessageTransporter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_LogMessageTransporter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LogMessageTransporter_2eproto;
namespace logmessagetransporter {
class AcknowledgeReply;
class AcknowledgeReplyDefaultTypeInternal;
extern AcknowledgeReplyDefaultTypeInternal _AcknowledgeReply_default_instance_;
class MessagesRequest;
class MessagesRequestDefaultTypeInternal;
extern MessagesRequestDefaultTypeInternal _MessagesRequest_default_instance_;
}  // namespace logmessagetransporter
PROTOBUF_NAMESPACE_OPEN
template<> ::logmessagetransporter::AcknowledgeReply* Arena::CreateMaybeMessage<::logmessagetransporter::AcknowledgeReply>(Arena*);
template<> ::logmessagetransporter::MessagesRequest* Arena::CreateMaybeMessage<::logmessagetransporter::MessagesRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace logmessagetransporter {

// ===================================================================

class MessagesRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:logmessagetransporter.MessagesRequest) */ {
 public:
  MessagesRequest();
  virtual ~MessagesRequest();

  MessagesRequest(const MessagesRequest& from);
  MessagesRequest(MessagesRequest&& from) noexcept
    : MessagesRequest() {
    *this = ::std::move(from);
  }

  inline MessagesRequest& operator=(const MessagesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessagesRequest& operator=(MessagesRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MessagesRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessagesRequest* internal_default_instance() {
    return reinterpret_cast<const MessagesRequest*>(
               &_MessagesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MessagesRequest* other);
  friend void swap(MessagesRequest& a, MessagesRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessagesRequest* New() const final {
    return CreateMaybeMessage<MessagesRequest>(nullptr);
  }

  MessagesRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MessagesRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MessagesRequest& from);
  void MergeFrom(const MessagesRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessagesRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "logmessagetransporter.MessagesRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_LogMessageTransporter_2eproto);
    return ::descriptor_table_LogMessageTransporter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string logMessages = 2;
  int logmessages_size() const;
  void clear_logmessages();
  static const int kLogMessagesFieldNumber = 2;
  const std::string& logmessages(int index) const;
  std::string* mutable_logmessages(int index);
  void set_logmessages(int index, const std::string& value);
  void set_logmessages(int index, std::string&& value);
  void set_logmessages(int index, const char* value);
  void set_logmessages(int index, const char* value, size_t size);
  std::string* add_logmessages();
  void add_logmessages(const std::string& value);
  void add_logmessages(std::string&& value);
  void add_logmessages(const char* value);
  void add_logmessages(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& logmessages() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_logmessages();

  // int32 size = 1;
  void clear_size();
  static const int kSizeFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:logmessagetransporter.MessagesRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> logmessages_;
  ::PROTOBUF_NAMESPACE_ID::int32 size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_LogMessageTransporter_2eproto;
};
// -------------------------------------------------------------------

class AcknowledgeReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:logmessagetransporter.AcknowledgeReply) */ {
 public:
  AcknowledgeReply();
  virtual ~AcknowledgeReply();

  AcknowledgeReply(const AcknowledgeReply& from);
  AcknowledgeReply(AcknowledgeReply&& from) noexcept
    : AcknowledgeReply() {
    *this = ::std::move(from);
  }

  inline AcknowledgeReply& operator=(const AcknowledgeReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AcknowledgeReply& operator=(AcknowledgeReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AcknowledgeReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AcknowledgeReply* internal_default_instance() {
    return reinterpret_cast<const AcknowledgeReply*>(
               &_AcknowledgeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AcknowledgeReply* other);
  friend void swap(AcknowledgeReply& a, AcknowledgeReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AcknowledgeReply* New() const final {
    return CreateMaybeMessage<AcknowledgeReply>(nullptr);
  }

  AcknowledgeReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AcknowledgeReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AcknowledgeReply& from);
  void MergeFrom(const AcknowledgeReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcknowledgeReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "logmessagetransporter.AcknowledgeReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_LogMessageTransporter_2eproto);
    return ::descriptor_table_LogMessageTransporter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  bool result() const;
  void set_result(bool value);

  // @@protoc_insertion_point(class_scope:logmessagetransporter.AcknowledgeReply)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  bool result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_LogMessageTransporter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessagesRequest

// int32 size = 1;
inline void MessagesRequest::clear_size() {
  size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MessagesRequest::size() const {
  // @@protoc_insertion_point(field_get:logmessagetransporter.MessagesRequest.size)
  return size_;
}
inline void MessagesRequest::set_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:logmessagetransporter.MessagesRequest.size)
}

// repeated string logMessages = 2;
inline int MessagesRequest::logmessages_size() const {
  return logmessages_.size();
}
inline void MessagesRequest::clear_logmessages() {
  logmessages_.Clear();
}
inline const std::string& MessagesRequest::logmessages(int index) const {
  // @@protoc_insertion_point(field_get:logmessagetransporter.MessagesRequest.logMessages)
  return logmessages_.Get(index);
}
inline std::string* MessagesRequest::mutable_logmessages(int index) {
  // @@protoc_insertion_point(field_mutable:logmessagetransporter.MessagesRequest.logMessages)
  return logmessages_.Mutable(index);
}
inline void MessagesRequest::set_logmessages(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:logmessagetransporter.MessagesRequest.logMessages)
  logmessages_.Mutable(index)->assign(value);
}
inline void MessagesRequest::set_logmessages(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:logmessagetransporter.MessagesRequest.logMessages)
  logmessages_.Mutable(index)->assign(std::move(value));
}
inline void MessagesRequest::set_logmessages(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  logmessages_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:logmessagetransporter.MessagesRequest.logMessages)
}
inline void MessagesRequest::set_logmessages(int index, const char* value, size_t size) {
  logmessages_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:logmessagetransporter.MessagesRequest.logMessages)
}
inline std::string* MessagesRequest::add_logmessages() {
  // @@protoc_insertion_point(field_add_mutable:logmessagetransporter.MessagesRequest.logMessages)
  return logmessages_.Add();
}
inline void MessagesRequest::add_logmessages(const std::string& value) {
  logmessages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:logmessagetransporter.MessagesRequest.logMessages)
}
inline void MessagesRequest::add_logmessages(std::string&& value) {
  logmessages_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:logmessagetransporter.MessagesRequest.logMessages)
}
inline void MessagesRequest::add_logmessages(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  logmessages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:logmessagetransporter.MessagesRequest.logMessages)
}
inline void MessagesRequest::add_logmessages(const char* value, size_t size) {
  logmessages_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:logmessagetransporter.MessagesRequest.logMessages)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MessagesRequest::logmessages() const {
  // @@protoc_insertion_point(field_list:logmessagetransporter.MessagesRequest.logMessages)
  return logmessages_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MessagesRequest::mutable_logmessages() {
  // @@protoc_insertion_point(field_mutable_list:logmessagetransporter.MessagesRequest.logMessages)
  return &logmessages_;
}

// -------------------------------------------------------------------

// AcknowledgeReply

// bool result = 1;
inline void AcknowledgeReply::clear_result() {
  result_ = false;
}
inline bool AcknowledgeReply::result() const {
  // @@protoc_insertion_point(field_get:logmessagetransporter.AcknowledgeReply.result)
  return result_;
}
inline void AcknowledgeReply::set_result(bool value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:logmessagetransporter.AcknowledgeReply.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace logmessagetransporter

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_LogMessageTransporter_2eproto
